[tool.poetry]
name = "mover"
version = "0.1.0"
description = "MOVER: Multi-Objective Optimization for VErsatile Materials Research"
authors = ["Conrard G. Tetsassi Feugmo <giresse.feugmo@gmail.com>"]
maintainers = [
   "Conrard G. Tetsassi Feugmo <giresse.feugmo@gmail.com>",
]
repository = "https://github.com/Feugmo-Group/mover"
readme = "README.md"
license = "MIT"


#classifiers = [
 #   "Topic :: Software Development :: Build Tools",
 #   "Topic :: Software Development :: Libraries :: Python Modules"
#]
#packages = [
#    { include = "my_package" },
#    { include = "extra_package/**/*.py" },
#]

[tool.poetry.dependencies]
python = "^3.9"
jupyter = "^1.0.0"
torch = "^2.0.1"
numpy = "^1.24.3"
plotly = "^5.14.1"
matplotlib = "^3.7.1"
scikit-learn = "^1.2.2"
aiida = "^1.0.1"
aiida-vasp = "^3.0.1"
botorch = "^0.9.2"
nbformat = "^4.2.0"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
flake8 = "^6.0.0"
pytest-cov = "^4.1.0"
pytest-mock = "^3.10.0"
isort = "^5.12.0"
pre-commit = "^3.3.2"
flake8-bandit = "^4.1.1"
flake8-docstrings = "^1.7.0"
poetry-githooks = "^2.0.0"
coverage = "^7.2.7"

# ...and can be installed only when explicitly requested
pylint = "^2.17.4"
pytest = "^7.3.1"
[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
httpretty = "^1.1.4"
sphinx = "^7.0.1"


# Python-style entrypoints and scripts are easily expressed
[tool.poetry.scripts]
my-script = "my_package:main"


[tool.black]
line-length = 120
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
| \.hg
| \.mypy_cache
| \.tox
| \.venv
| _build
| buck-out
| build
)/
'''

[tool.flake8]
max-line-length = 120
extend-ignore = ["D203", "E203", "E251", "E266", "E302", "E305", "E401", "E402", "E501", "F401", "F403", "W503"]
exclude = [".git", "__pycache__", "dist"]
max-complexity = 10

[tool.isort]
atomic = true
profile = "black"
line_length = 120
skip_gitignore = true

[tool.pylint]
max-line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
